### ISSUE TITLE
Broken!

### ISSUE THREAD

**Issue by thalesfsp** [spencermountain/Freebase.js#8]
npm http GET https://registry.npmjs.org/freebase
npm http 304 https://registry.npmjs.org/freebase
npm http GET https://registry.npmjs.org/freebase/-/freebase-2.1.23.tgz
npm http 404 https://registry.npmjs.org/freebase/-/freebase-2.1.23.tgz
npm ERR! fetch failed https://registry.npmjs.org/freebase/-/freebase-2.1.23.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "install" "freebase"
npm ERR! cwd /Users/codewarrior/dev/nodejs/projects/shift-exchange
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/codewarrior/dev/nodejs/projects/shift-exchange/npm-debug.log
npm ERR! not ok code 0

**Comment by martindevans** [comment]
I'm having exactly the same problem :(

Version 2.1.17 (http://registry.npmjs.org/freebase/-/freebase-2.1.17.tgz) downloads fine but 2.1.21 (the next version after 2.1.17) and later versions seem to be broken.

Looking at the timestamps for the broken versions:

"2.1.21": "2014-02-26T17:48:29.517Z",
"2.1.22": "2014-02-26T19:37:07.132Z",
"2.1.23": "2014-02-26T19:40:15.001Z"

It looks like you may have been in a little bit of a rush getting a fixed version out and forgot something critical? I don't think there's any way for me to fix this otherwise I'd do it and submit a PR.

The bandaid fix I'm employing for now is simply:
    npm install freebase@2.1.17 --save

**Comment by sughodke** [comment]
ditto...

Thanks for the workaround Martin.

**Comment by spencermountain** [comment]
sorry guys, fixed now
thanks for the heads-up
